# Generated by Django 5.0.2 on 2024-02-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts_post',
        ),
    ]
