# Generated by Django 5.0.2 on 2024-02-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user_alter_post_options_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
    ]
